### DISCUSSION TITLE
Format for lockout and priority files

### DISCUSSION THREAD

**Discussion by john-** [john-/ham2mon#30] [Q&A]
Ham2mon uses different formats for priority files and lockout files.  Also, it does not support a file for general configuration of frequency metadata. For frequencies, it only displays the frequency in Mhz.  It would be good if it also displayed user friendly labels for scanned channels.

What are your thoughts on a file with a YAML format something like this:
```
frequencies:
  - label: "Active mobile channel"
    single: 450.225
    priority: true
  - label: "Mobile UHF of interest"
    lo: 450
    hi: 452
    priority: true
  - label: "data"
    single: 151.675
    lockout: true
  - label: "FRS channels 1-7"
    lo: 462.5625
    hi: 462.7125
    lockout: true
  - label: "70cm FM Simplex Calling"
    single: 446.0
  - label: "FRS channels 8-14"
    lo: 467.5625
    hi: 467.7125
```
This format would consolidate the lockout and priority files as well as provide user friendly descriptions for frequencies in general.

The UI could be modified to display the label instead of (or in addition to) the frequency.

The format can be extended with other metadata.  In addition, other configuration information could be added (command line options supplied would take precedent).

I haven't though through how practical this is yet.   There is current;y is no "save" option for priority or lockout information so that would need to be considered.
